// Module 0 (Shared Platform & Identity) tables, hand-written against the live
// Supabase database rather than generated by `drizzle-kit introspect`.
//
// Why hand-written: as of Phase 0, DATABASE_URL is not available in this
// environment (the owner has to add it — it needs the database password),
// and `drizzle-kit introspect` needs a live connection. Every column below
// was verified read-only, on 2026-09-18, against project `nburswxjpukntgdwuyme`
// (atllanta) via `information_schema.columns` and the table's PRIMARY KEY
// constraint (see task-3-report.md for the exact queries and full output).
// Nothing here was guessed.
//
// Scope: only the 10 platform tables this phase's brief calls for
// (organizations, users, departments, teams, invitations, audit_logs,
// events, notifications, files, feature_access). Every column that exists
// on each of those tables today is modelled — later CLAUDE.md additions
// such as org_modules, roles, role_permissions, custom_role_id, and the
// AI-quota/webhook tables are out of scope for this file and are not
// modelled here.
//
// Re-verified 2026-09-22 (Phase 1 item 1): every column, type, nullability
// and default matches the live database, and the 14 foreign keys declared
// with `.references()` are exactly the live FK constraints. They describe the
// existing schema only — nothing here is pushed or migrated.
//
// Once DATABASE_URL exists, run `npm run db:introspect` to regenerate this
// file from the live schema and diff the result against what's below before
// replacing anything.
import {
  pgTable,
  uuid,
  text,
  boolean,
  integer,
  numeric,
  timestamp,
  jsonb,
  date,
} from "drizzle-orm/pg-core";

export const organizations = pgTable("organizations", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  slug: text("slug"),
  logoUrl: text("logo_url"),
  timezone: text("timezone").default("Asia/Kolkata"),
  currency: text("currency").default("INR"),
  dateFormat: text("date_format").default("DD/MM/YYYY"),
  planTier: text("plan_tier").notNull().default("starter"),
  paymentStatus: text("payment_status").notNull().default("trial"),
  orgType: text("org_type").notNull(),
  crmEnabled: boolean("crm_enabled").notNull().default(true),
  partnerCrmEnabled: boolean("partner_crm_enabled").notNull().default(false),
  creditsBalance: integer("credits_balance").default(200),
  creditOverageMode: text("credit_overage_mode").default("soft_bill"),
  creditsIncludedMonthly: integer("credits_included_monthly").default(200),
  commissionPercent: numeric("commission_percent").default("0"),
  trialStartedAt: timestamp("trial_started_at", { withTimezone: true }).defaultNow(),
  // Live default is `now() + interval '14 days'`, left to Postgres (see expiresAt).
  trialEndsAt: timestamp("trial_ends_at", { withTimezone: true }),
  trialCandidateCap: integer("trial_candidate_cap").default(25),
  maxTrialExtensionDays: integer("max_trial_extension_days").default(30),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const users = pgTable("users", {
  // References auth.users; no default here (Supabase auth assigns the id).
  id: uuid("id").primaryKey(),
  orgId: uuid("org_id").references(() => organizations.id),
  fullName: text("full_name"),
  email: text("email"),
  phone: text("phone"),
  avatarUrl: text("avatar_url"),
  role: text("role").default("member"),
  designation: text("designation"),
  departmentId: uuid("department_id").references(() => departments.id),
  teamId: uuid("team_id").references(() => teams.id),
  reportingManagerId: uuid("reporting_manager_id"),
  status: text("status").default("active"),
  dateOfJoining: date("date_of_joining"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const departments = pgTable("departments", {
  id: uuid("id").primaryKey().defaultRandom(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organizations.id),
  name: text("name").notNull(),
  headId: uuid("head_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const teams = pgTable("teams", {
  id: uuid("id").primaryKey().defaultRandom(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organizations.id),
  departmentId: uuid("department_id")
    .notNull()
    .references(() => departments.id),
  name: text("name").notNull(),
  leadId: uuid("lead_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const invitations = pgTable("invitations", {
  id: uuid("id").primaryKey().defaultRandom(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organizations.id),
  email: text("email").notNull(),
  role: text("role").notNull().default("member"),
  invitedBy: uuid("invited_by"),
  status: text("status").notNull().default("pending"),
  fullName: text("full_name"),
  phone: text("phone"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  // Live default is `now() + interval '7 days'`; Drizzle has no portable way
  // to express that as a column default, so it is left to Postgres.
  expiresAt: timestamp("expires_at", { withTimezone: true }),
});

export const auditLogs = pgTable("audit_logs", {
  id: uuid("id").primaryKey().defaultRandom(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organizations.id),
  userId: uuid("user_id").references(() => users.id),
  module: text("module").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: uuid("entity_id").notNull(),
  action: text("action").notNull(),
  oldValues: jsonb("old_values"),
  newValues: jsonb("new_values"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const events = pgTable("events", {
  id: uuid("id").primaryKey().defaultRandom(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organizations.id),
  eventType: text("event_type").notNull(),
  actorId: uuid("actor_id"),
  payload: jsonb("payload").notNull().default({}),
  status: text("status").default("pending"),
  attempts: integer("attempts").default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  processedAt: timestamp("processed_at", { withTimezone: true }),
  lockedAt: timestamp("locked_at", { withTimezone: true }),
  lastError: text("last_error"),
  failedAt: timestamp("failed_at", { withTimezone: true }),
});

export const notifications = pgTable("notifications", {
  id: uuid("id").primaryKey().defaultRandom(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organizations.id),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  title: text("title").notNull(),
  body: text("body"),
  module: text("module").notNull(),
  entityType: text("entity_type"),
  entityId: uuid("entity_id"),
  channel: text("channel").notNull().default("in_app"),
  status: text("status").default("unread"),
  sentAt: timestamp("sent_at", { withTimezone: true }).defaultNow(),
  emailStatus: text("email_status").notNull().default("none"),
  emailedAt: timestamp("emailed_at", { withTimezone: true }),
});

export const files = pgTable("files", {
  id: uuid("id").primaryKey().defaultRandom(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organizations.id),
  uploadedBy: uuid("uploaded_by").notNull(),
  fileName: text("file_name").notNull(),
  filePath: text("file_path").notNull(),
  fileSize: integer("file_size"),
  mimeType: text("mime_type"),
  entityType: text("entity_type"),
  entityId: uuid("entity_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const featureAccess = pgTable("feature_access", {
  id: uuid("id").primaryKey().defaultRandom(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organizations.id),
  subjectType: text("subject_type").notNull(), // 'role' | 'user'
  subjectKey: text("subject_key").notNull(),
  featureKey: text("feature_key").notNull(),
  allowed: boolean("allowed").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
